Repository openwall/john, pull requests merged in 2018-07, with the labels that each got.

#3295 Add support for cracking Telegram Desktop passcodes
  run/telegram2john.py
  src/aes_ige.h
  src/aes_ige_plug.c
  src/telegram_common.h
  src/telegram_common_plug.c
  src/telegram_fmt_plug.c
Labels: New format, enhancement

#3296 OpenCL support for cracking Telegram Desktop passcodes
  src/opencl/telegram_kernel.cl
  src/opencl_aes.h
  src/opencl_telegram_fmt_plug.c
Labels: enhancement

#3298 Bunch of trivial fixes
  src/opencl_androidbackup_fmt_plug.c
  src/telegram_fmt_plug.c
Labels: Maintenance/cleanup

#3299 Improve auditing documentation a bit
  doc/Auditing-Kerio-Connect.md
Labels: documentation

#3297 Support for FortiGate SHA256 format
  src/FG2_fmt_plug.c
Labels: New format

#3304 Parsing fixes for telegram2john.py
  run/telegram2john.py
Labels: Maintenance/cleanup, bug

#3303 Add support for cracking SAP's PSE files
  run/pse2john.py
  src/sap_pse_fmt_plug.c
Labels: New format, New tool

#3306 Add OpenCL support for cracking SAP's PSE files
  src/opencl/sap_pse_kernel.cl
  src/opencl_sappse_fmt_plug.c
  src/sap_pse_common.h
  src/sap_pse_common_plug.c
  src/sap_pse_fmt_plug.c
Labels: enhancement

#3317 Add OpenCL support for cracking Tezos keys
  run/tezos2john.py
  src/opencl/tezos_kernel.cl
  src/opencl_tezos_fmt_plug.c
  src/tezos_common.h
  src/tezos_common_plug.c
  src/tezos_fmt_plug.c
Labels: enhancement

#3322 Add another test vector to SIP format
  src/sip_fmt_plug.c
Labels: Maintenance/cleanup

#3330 OpenCL support for cracking SSH keys - Initial Cut
  src/opencl/ssh_kernel.cl
  src/opencl_ssh_fmt_plug.c
  src/ssh_common.h
  src/ssh_common_plug.c
  src/ssh_fmt_plug.c
  src/ssh_variable_code.h
Labels: enhancement

#3335 Fix recent incorrect buffer resizing in charset handling code
  src/charset.c
  src/charset.h
Labels: bug

#3341 Autoconf: Add a way to check if -Wno-foo is supported.
  src/configure
  src/configure.ac
  src/m4/jtr_utility_macros.m4
Labels: bug
