Repository openwall/john, pull requests merged in 2018-11, with the labels that each got.

#3449 Add support for cracking SolarWinds Orion hashes
  src/opencl/solarwinds_kernel.cl
  src/opencl_solarwinds_fmt_plug.c
  src/solarwinds_common.h
  src/solarwinds_common_plug.c
  src/solarwinds_fmt_plug.c
Labels: New format

#3453 Fix comment styling a bit
  src/opencl_agilekeychain_fmt_plug.c
  src/opencl_blockchain_fmt_plug.c
  src/opencl_enpass_fmt_plug.c
  src/opencl_keychain_fmt_plug.c
  src/opencl_keyring_fmt_plug.c
  src/opencl_rar5_fmt_plug.c
  src/opencl_sha1crypt_fmt_plug.c
  src/opencl_strip_fmt_plug.c
  src/opencl_tc_fmt_plug.c
  src/opencl_wpapmk_fmt_plug.c
  src/opencl_wpapsk_fmt_plug.c
  src/opencl_zip_fmt_plug.c
Labels: Maintenance/cleanup

#3471 Expose min_length constant in rules
  doc/RULES
  src/rules.c
Labels: enhancement
