Repository openwall/john, pull requests merged in 2018-10, with the labels that each got.

#3416 Add OpenCL support for cracking 1Password Cloud Keychains
  src/cloudkeychain_common.h
  src/cloudkeychain_common_plug.c
  src/cloudkeychain_fmt_plug.c
  src/opencl/cloudkeychain_kernel.cl
  src/opencl_cloudkeychain_fmt_plug.c
Labels: enhancement

#3440 Tweak error/warning handling in gcc-8
  src/configure
  src/configure.ac
Labels: notes/external issues

#3442 Fix up our issue template language
  .github/issue_template.md
Labels: Maintenance/cleanup

#3446 Enable ADXCRYPT to run on BE (e.g. mips64) machines
  src/adxcrypt_fmt_plug.c
Labels: bug, enhancement
