Repository openwall/john, pull requests merged in 2018-12, with the labels that each got.

#3481 Support Python 3 in ml2john.py utility
  run/ml2john.py
Labels: enhancement, portability

#3480 cracker.c: Warn about too few candidate passwords. See #3386
  run/john.conf
  src/cracker.c
  src/params.h
Labels: enhancement

#3486 Add support for RACF KDFAES hashes (v0.15)
  src/racf_kdfaes_fmt_plug.c
Labels: New format

#3488 Add support for QAS vas_auth
  run/dynamic.conf
Labels: enhancement

#3491 [MAINT] Rename ml2john.py to mac2john.py
  run/mac2john.py
Labels: Maintenance/cleanup

#3506 Add an alternate implementation of mac2john.py script
  run/mac2john-alt.py
Labels: New tool, enhancement

#3530 [MAINT] Fix an informational message regarding KRB stuff
  run/ccache2john.py
  run/kirbi2john.py
Labels: Maintenance/cleanup

#3560 OpenCL support for cracking AxCrypt 2.x containers
  src/axcrypt_common.h
  src/axcrypt_common_plug.c
  src/axcrypt_fmt_plug.c
  src/axcrypt_variable_code.h
  src/opencl/axcrypt2_kernel.cl
  src/opencl_axcrypt2_fmt_plug.c
  src/opencl_axcrypt_fmt_plug.c
Labels: enhancement

#3570 Make DiskCryptor format functional on BE machines
  src/diskcryptor_common_plug.c
Labels: portability
