Repository openwall/john, pull requests merged in 2018-05, with the labels that each got.

#3240 Add support for cracking Adobe AEM hashes
  run/aem2john.py
  src/opencl_sspr_fmt_plug.c
  src/sspr_common.h
  src/sspr_common_plug.c
  src/sspr_fmt_plug.c
Labels: New tool

#3258 Many OpenCL formats: Use new scheme of LWS=NULL
  src/opencl/md4_kernel.cl
  src/opencl/md5_kernel.cl
  src/opencl/nt_kernel.cl
  src/opencl/salted_sha_kernel.cl
  src/opencl/sha1_kernel.cl
  src/opencl_7z_fmt_plug.c
  src/opencl_agilekeychain_fmt_plug.c
  src/opencl_ansible_fmt_plug.c
  src/opencl_bitwarden_fmt_plug.c
  src/opencl_blockchain_fmt_plug.c
  src/opencl_electrum_modern_fmt_plug.c
  src/opencl_ethereum_fmt_plug.c
  src/opencl_ethereum_presale_fmt_plug.c
  src/opencl_fvde_fmt_plug.c
  src/opencl_gpg_fmt_plug.c
  src/opencl_hash_check_128_plug.c
  src/opencl_keepass_fmt_plug.c
  src/opencl_keychain_fmt_plug.c
  src/opencl_lastpass_cli_fmt_plug.c
  src/opencl_lastpass_fmt_plug.c
  src/opencl_md5crypt_fmt_plug.c
  src/opencl_mysqlsha1_fmt_plug.c
  src/opencl_notes_fmt_plug.c
  src/opencl_nt_fmt_plug.c
  src/opencl_odf_fmt_plug.c
  src/opencl_pbkdf2_hmac_sha256_fmt_plug.c
  src/opencl_pbkdf2_hmac_sha512_fmt_plug.c
  src/opencl_pfx_fmt_plug.c
  src/opencl_pwsafe_fmt_plug.c
  src/opencl_rar5_fmt_plug.c
  src/opencl_rar_fmt_plug.c
  src/opencl_rawmd5_fmt_plug.c
  src/opencl_rawsha1_fmt_plug.c
  src/opencl_rawsha512_fmt_plug.c
  src/opencl_salted_sha_fmt_plug.c
  src/opencl_sl3_fmt_plug.c
  src/opencl_sspr_fmt_plug.c
  src/opencl_strip_fmt_plug.c
  src/opencl_tc_fmt_plug.c
  src/opencl_xsha512_fmt_plug.c
  src/opencl_zip_fmt_plug.c
Labels: enhancement

#3260 Add support for cracking Android Backups
  run/androidbackup2john.py
  src/androidbackup_fmt_plug.c
Labels: New format, New tool
