Repository openwall/john, pull requests merged in 2019-05, with the labels that each got.

#3908 Unsplit test vectors that were split through use of backslashes inside the string constant.
  src/openbsdsoftraid_variable_code.h
  src/pkzip_fmt_plug.c
Labels: Maintenance/cleanup

#3931 Rename CHANGES-jumbo.git to CHANGES-JUMBO and update it.
  doc/CHANGES-jumbo
  doc/CHANGES-jumbo.git
  doc/CREDITS-jumbo
Labels: Maintenance/cleanup

#3939 Define RELEASE_BUILD
  src/Makefile.in
  src/Makefile.legacy
  src/params.h
Labels: Maintenance/cleanup

#3941 Re-enable some formats on CI
  .ci/disable_formats.sh
Labels: testing

#3943 CI: add more tests
  .circleci/config.yml
Labels: testing

#3987 Add --rules-skip-nop option
  src/john.c
  src/loader.c
  src/options.c
  src/options.h
  src/rules.c
  src/wordlist.c
Labels: enhancement
