Repository openwall/john, pull requests merged in 2019-01, with the labels that each got.

#3580 first version of unit testing code. Some changes needed in common.c/…
  src/Makefile.in
  src/Makefile.legacy
  src/tests/NESSIE/BCHASH-Rijndael-128.unverified.test-vectors.txt
  src/tests/NESSIE/BCHASH-Rijndael-256.unverified.test-vectors.txt
  src/tests/NESSIE/Md4-128.unverified.test-vectors.txt
  src/tests/NESSIE/Md5-128.unverified.test-vectors.txt
  src/tests/NESSIE/Ripemd-160.test-vectors.txt
  src/tests/NESSIE/Sha-2-256.unverified.test-vectors.txt
  src/tests/NESSIE/Sha-2-384.unverified.test-vectors.txt
  src/tests/NESSIE/Sha-2-512.unverified.test-vectors.txt
  src/tests/NESSIE/Tiger-192.test-vectors.txt
  src/tests/NESSIE/Whirlpool-Orig-512.verified.test-vectors.txt
  src/tests/NESSIE/Whirlpool-Tweak-512.verified.test-vectors.txt
  src/tests/NIST_CAVS/SHA224LongMsg.rsp
  src/tests/NIST_CAVS/SHA224Monte.rsp
  src/tests/NIST_CAVS/SHA224ShortMsg.rsp
  src/tests/NIST_CAVS/SHA256LongMsg.rsp
  src/tests/NIST_CAVS/SHA256Monte.rsp
  src/tests/NIST_CAVS/SHA256ShortMsg.rsp
  src/tests/NIST_CAVS/SHA384LongMsg.rsp
  src/tests/NIST_CAVS/SHA384Monte.rsp
  src/tests/NIST_CAVS/SHA384ShortMsg.rsp
  src/tests/NIST_CAVS/SHA512LongMsg.rsp
  src/tests/NIST_CAVS/SHA512Monte.rsp
  src/tests/NIST_CAVS/SHA512ShortMsg.rsp
  src/tests/unit_tests.c
Labels: testing

#3586 unit-tests target: Fix backwards dependencies.
  .gitignore
  src/Makefile.in
  src/Makefile.legacy
  src/configure
  src/configure.ac
  src/tests/unit-tests.c
Labels: testing

#3604 Re-print the single mode warning about disabled recursion…
  src/john.c
  src/single.c
  src/single.h
Labels: enhancement

#3623 unique: Add 64-bit support, for large buffers/hash tables, and other tweaks.
  src/params.h
  src/unique.c
Labels: enhancement

#3621 Add radius2john python script
  run/radius2john.py
Labels: New tool, enhancement
