Repository openwall/john, pull requests merged in 2021-12, with the labels that each got.

#4909 7z formats: Add support for Delta encoding
  run/7z2john.pl
  src/7z_common.h
  src/7z_common_plug.c
  src/Makefile.in
  src/Makefile.legacy
  src/lzma/Delta.c
  src/lzma/Delta.h
Labels: enhancement

#4917 Change a confusing error message when requesting an empty format class
  src/formats.c
  src/formats.h
  src/john.c
Labels: enhancement

#4921 Wordlist mode: Support --wordlist=<fifo>
  src/wordlist.c
Labels: enhancement

#4927 Bugfix for 'vector' format class
  src/formats.c
  src/formats.h
  src/opencl_common.c
Labels: bug

#4942 cisco2john: Ensure "password 7" obfuscation is properly decoded
  run/cisco2john.pl
Labels: bug

#4947 Dynamic format: Don't un-hex ciphertexts too early.
  src/dynamic.h
  src/dynamic_fmt.c
  src/dynamic_utils.c
  src/formats.c
  src/loader.c
  src/logger.c
Labels: bug

#4949 Don't log " - OpenCL LWS: 7, GWS: 49 (7 blocks)" for self-test
  src/opencl_autotune.h
Labels: maintenance/cleanup

#4950 Initial support for ENCDataVault
  doc/NEWS
  doc/README-ENCDataVault.md
  run/encdatavault2john.py
  src/encdatavault_fmt_plug.c
Labels: new format

#4972 Fix for ENCDataVault format: Mute spurious warnings
  src/encdatavault_fmt_plug.c
Labels: bug
